version: "3.7"

##############
#
# Para migrar o banco do Woofed CRM, execute o comando abaixo no console do container Principal:
#
# bundle exec rails db:create db:migrate
#
# Acesso o Link e escolha sua Versão:
#
# https://hub.docker.com/r/douglara/woofedcrm/tags

services:

  woofedcrm:
    image: douglara/woofedcrm:development-e8bd47254d620a432e7d3fa729cb4b62cb95fabb
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    ports:
      - "3001:3000"
    volumes:
      - woofedcrm_data:/app/public/assets
    networks:
      - minha_rede
    environment:
      - FRONTEND_URL=http://localhost:3001
      - SECRET_KEY_BASE=7a466b84181545c3ab1f03cc45aeae8e031ed950c6dc1d35385fff5b595ad75bc78ff2aa33640049a7fc94a9c83bf1c665ee0eadfda0c79b8ee36ed83263bc8a
      - ENABLE_USER_SIGNUP=true
      - RAILS_ENV=production
      - RACK_ENV=production
      - NODE_ENV=production
      - RAILS_LOG_LEVEL=debug
      - MOTOR_AUTH_USERNAME=astraonlineweb@gmail.com
      - MOTOR_AUTH_PASSWORD=Mfcd62!!Mfcd62!!
      - EVOLUTION_API_ENDPOINT=http://evolution_astra:8080
      - EVOLUTION_API_ENDPOINT_TOKEN=b45db89a9f853402af79da49a518d8fe
      - DATABASE_URL=postgres://postgres:Mfcd62!!Mfcd62!!@postgrespgvector:5432/woofedcrm
      - REDIS_URL=redis://redis:6379/0
      - ACTIVE_STORAGE_SERVICE=local
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

  sidekiq:
    image: douglara/woofedcrm:development-e8bd47254d620a432e7d3fa729cb4b62cb95fabb
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - woofedcrm_data:/app/public/assets
    networks:
      - minha_rede
    environment:
      - FRONTEND_URL=http://localhost:3001
      - SECRET_KEY_BASE=7a466b84181545c3ab1f03cc45aeae8e031ed950c6dc1d35385fff5b595ad75bc78ff2aa33640049a7fc94a9c83bf1c665ee0eadfda0c79b8ee36ed83263bc8a
      - ENABLE_USER_SIGNUP=true
      - RAILS_ENV=production
      - RACK_ENV=production
      - NODE_ENV=production
      - RAILS_LOG_LEVEL=debug
      - MOTOR_AUTH_USERNAME=astraonlineweb@gmail.com
      - MOTOR_AUTH_PASSWORD=Mfcd62!!Mfcd62!!
      - EVOLUTION_API_ENDPOINT=http://evolution_astra:8080
      - EVOLUTION_API_ENDPOINT_TOKEN=b45db89a9f853402af79da49a518d8fe
      - DATABASE_URL=postgres://postgres:Mfcd62!!Mfcd62!!@postgrespgvector:5432/woofedcrm
      - REDIS_URL=redis://redis:6379/0
      - ACTIVE_STORAGE_SERVICE=local
      
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

  good_job:
    image: douglara/woofedcrm:development-e8bd47254d620a432e7d3fa729cb4b62cb95fabb
    command: bundle exec good_job
    volumes:
      - woofedcrm_data:/app/public/assets
    networks:
      - minha_rede
    environment:
      - FRONTEND_URL=http://localhost:3001
      - SECRET_KEY_BASE=7a466b84181545c3ab1f03cc45aeae8e031ed950c6dc1d35385fff5b595ad75bc78ff2aa33640049a7fc94a9c83bf1c665ee0eadfda0c79b8ee36ed83263bc8a
      - ENABLE_USER_SIGNUP=true
      - RAILS_ENV=production
      - RACK_ENV=production
      - NODE_ENV=production
      - RAILS_LOG_LEVEL=debug
      - MOTOR_AUTH_USERNAME=astraonlineweb@gmail.com
      - MOTOR_AUTH_PASSWORD=Mfcd62!!Mfcd62!!
      - EVOLUTION_API_ENDPOINT=http://evolution_astra:8080
      - EVOLUTION_API_ENDPOINT_TOKEN=b45db89a9f853402af79da49a518d8fe
      - DATABASE_URL=postgres://postgres:Mfcd62!!Mfcd62!!@postgrespgvector:5432/woofedcrm
      - REDIS_URL=redis://redis:6379/0
      - ACTIVE_STORAGE_SERVICE=local

    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M


volumes:
  woofedcrm_data:
    external: true
    name: woofedcrm_data

networks:
  minha_rede:
    name: minha_rede
    external: true
